apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: rjohnson
spec:
  template:
    spec:
      containers:
        - image: docker.io/saparchitect/helloworld-go
          env:
            - name: TARGET
              value: "Ricks Test 2 from Hello World"